title: "My Jekyll Blog"
description: "A blog documenting my projects, including a PDF-to-LaTeX converter!"
theme: minima

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

navigation:
  - title: "Home"
    url: "/"
  - title: "PDF to LaTeX"
    url: "https://pdkhasanthika.pythonanywhere.com/" # Link to your Flask app

